
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Entry TextBoxIP;
	
	private global::Gtk.Button BtnClearStatus;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView TextViewStatus;
	
	private global::Gtk.Button BtnDisconnect;
	
	private global::Gtk.Button BtnCall;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.TextBoxIP = new global::Gtk.Entry ();
		this.TextBoxIP.CanFocus = true;
		this.TextBoxIP.Name = "TextBoxIP";
		this.TextBoxIP.IsEditable = true;
		this.TextBoxIP.InvisibleChar = '•';
		this.fixed1.Add (this.TextBoxIP);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.TextBoxIP]));
		w1.X = 154;
		w1.Y = 21;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BtnClearStatus = new global::Gtk.Button ();
		this.BtnClearStatus.CanFocus = true;
		this.BtnClearStatus.Name = "BtnClearStatus";
		this.BtnClearStatus.UseUnderline = true;
		this.BtnClearStatus.Label = global::Mono.Unix.Catalog.GetString ("Clear Status");
		this.fixed1.Add (this.BtnClearStatus);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BtnClearStatus]));
		w2.X = 376;
		w2.Y = 276;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.HeightRequest = 15;
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("IP Address");
		this.fixed1.Add (this.label1);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
		w3.X = 34;
		w3.Y = 22;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Call Status");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w4.X = 30;
		w4.Y = 100;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.TextViewStatus = new global::Gtk.TextView ();
		this.TextViewStatus.WidthRequest = 300;
		this.TextViewStatus.HeightRequest = 175;
		this.TextViewStatus.CanFocus = true;
		this.TextViewStatus.Name = "TextViewStatus";
		this.GtkScrolledWindow.Add (this.TextViewStatus);
		this.fixed1.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
		w6.X = 19;
		w6.Y = 129;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BtnDisconnect = new global::Gtk.Button ();
		this.BtnDisconnect.CanFocus = true;
		this.BtnDisconnect.Name = "BtnDisconnect";
		this.BtnDisconnect.UseUnderline = true;
		this.BtnDisconnect.Label = global::Mono.Unix.Catalog.GetString ("Disconnect");
		this.fixed1.Add (this.BtnDisconnect);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BtnDisconnect]));
		w7.X = 151;
		w7.Y = 64;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.BtnCall = new global::Gtk.Button ();
		this.BtnCall.CanFocus = true;
		this.BtnCall.Name = "BtnCall";
		this.BtnCall.UseUnderline = true;
		this.BtnCall.Label = global::Mono.Unix.Catalog.GetString ("Call");
		this.fixed1.Add (this.BtnCall);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.BtnCall]));
		w8.X = 269;
		w8.Y = 67;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 483;
		this.DefaultHeight = 338;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.BtnClearStatus.Clicked += new global::System.EventHandler (this.OnBtnClearStatusClicked);
		this.BtnDisconnect.Clicked += new global::System.EventHandler (this.OnBtnDisconnectClicked);
		this.BtnCall.Clicked += new global::System.EventHandler (this.OnBtnCallClicked);
	}
}
